name: build / compile
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  webwallet-js:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps: 
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1.4.2
        with:
          node-version: '12.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup Cache
        uses: actions/cache@v1.2.0
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: reactnative-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            reactnative-yarn-

      - name: Install npm dependencies
        run: |
          yarn --network-concurrency 1 --network-timeout 120000

      - name: Typescript to JS
        run: |
          node ./node_modules/typescript/bin/tsc --project tsconfig.prod.json


